# Generated by Django 5.2.7 on 2025-10-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
