# Generated by Django 5.2.7 on 2025-10-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_alter_vehicle_kilometraje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
    ]
