# Generated by Django 5.2.7 on 2025-10-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_options_alter_vehicle_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
