# Generated by Django 5.2.7 on 2025-10-28 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicleimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='vehiculos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
