# Generated by Django 5.2.7 on 2025-11-04 19:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField(default=0)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tasa_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.19'), max_digits=4)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='tarjeta', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='vehicles.vehicle')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
